{application,liewang,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{liewang_app,[]}},
              {env,[]},
              {modules,[building_server,lib_misc,lib_parameter,liewang,
                        liewang_app,liewang_sup,role_server,test]}]}.
